# Service users

- user_config:

    - system-user-tags:

       - name: 
         path: realProject
         isSystemUser: true
         

    - system-user-content:

       - name: 
         path: realProject
         isSystemUser: true
         

    - system-user-home:

       - name: 
         path: realProject
         isSystemUser: true


- ace_config:

    - system-user-tags:

       - path: /etc/tags
         permission: allow
         actions: read
         privileges: 


    - system-user-content:

       - path: /content
         permission: allow
         actions: read
         privileges: 


    - system-user-home:

       - path: /home
         permission: allow
         actions: read
         privileges: 
